import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
       <body className="bg-background font-popins dark:bg-[#020817]">   
        {children}
        <Toaster richColors position="top-right" />
       </body>
    </html>
  );
}
